version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Noman
      MONGO_INITDB_ROOT_PASSWORD: mian3434
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Noman
      ME_CONFIG_MONGODB_ADMINPASSWORD: mian3434
      ME_CONFIG_MONGODB_URL: mongodb://Noman:mian3434@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  labmanbackend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labmanbackend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=local
    env_file:
      - ./backend/.env.local

  labmanfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labmanfrontend
    restart: always
    ports:
      - "3000:80"

volumes:
  mongo-data:
